consul:
 image: progrium/consul
 hostname: navis
 ports:
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"
 command: -server -bootstrap -ui-dir /ui -dc navis
 restart: always

vault:
 build: .
 cap_add:
  - IPC_LOCK
 ports:
  - 8200:8200
 links:
  - consul
