elasticsearch:
 build: elasticsearch
 ports:
  - "9200:9200"
  - "9300:9300"

logstash:
 build: logstash
 ports:
  - "5000:5000"
  - "5000:5000/udp"
 links:
  - elasticsearch
 
kibana:
 build: kibana
 ports:
  - "80:80"
 
#logspout:
# image: gliderlabs/logspout
# volumes:
#  - /var/run/docker.sock:/tmp/docker.sock
# environment:
#  LOGSPOUT: ignore
# links:
#  - logstash
# command: syslog://logstash:5000
